name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install -g nx && npm ci

      - name: Build library
        run: npx nx build ui-components --configuration=production

      - name: Configure Git
        run: |
          git config --global user.name "nalvac"
          git config --global user.email "vacna197@gmail.com"

      - name: Prepare release branch
        run: |
          git branch -D release || true
          git checkout --orphan release

          git reset --hard

      - name: Copy dist to root
        run: |
          cp -r dist/ui-components/* ./
          rm -rf dist node_modules

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git commit -m "Release ${GITHUB_REF_NAME}"
          git push -f origin release
