name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install -g nx && npm ci

      - name: Build library
        run: npx nx build ui-components --configuration=production

      - name: Configure Git
        run: |
          git config --global user.name "nalvac"
          git config --global user.email "vacna197@gmail.com"

      - name: Prepare release branch
        run: |
          # Crée une nouvelle branche vierge
          git checkout --orphan temp-release
          
          # Copie uniquement les fichiers nécessaires
          cp -r dist/ui-components .

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure l'authentification
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          # Commit et remplace la branche release
          git add -f .
          git commit -m "Release ${GITHUB_REF_NAME}"
          git branch -D release || true
          git branch -m release
          git push -f origin release
