name: Release
on:
  push:
    tags:
      - 'v*'  # Déclenché pour les tags comme v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour les opérations git ultérieures

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install -g nx && npm ci

      - name: Build library
        run: npx nx build ui-components

      - name: Configure Git
        run: |
          git config --global user.name "nalvac"
          git config --global user.email "vacna197@gmail.com"

      - name: Prepare release branch
        run: |
          git checkout --orphan release
          cp -r dist/ui-components/* .

      - name: Commit and push to release branch
        run: |
          git add .
          git commit -m "Release ${GITHUB_REF_NAME}"
          git push -f origin release
