name: Release

# 1️⃣ On autorise explicitement le push
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 2️⃣ On s’assure de persister le GITHUB_TOKEN pour les pushes
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install -g nx && npm ci

      - name: Build library
        run: npx nx build ui-components --configuration=production

      - name: Configure Git
        run: |
          git config --global user.name "nalvac"
          git config --global user.email "vacna197@gmail.com"

      - name: Prepare release branch
        run: |
          # Si la branche release existe déjà, on la supprime localement
          git branch -D release || true
          # On crée la branche release à partir de HEAD
          git checkout --orphan release

          # On supprime tout (sinon on garde les fichiers de l'app)
          git reset --hard

      - name: Copy dist to root
        run: |
          # Ici, ui-components est le nom de ta lib ; adapte si besoin
          cp -r dist/ui-components/* ./
          # On peut enlever le dossier dist/ si tu ne le veux pas :
          rm -rf dist

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git commit -m "Release ${GITHUB_REF_NAME}"
          # 3️⃣ On pousse en forçant la branche release
          git push -f origin release
